### PR TITLE
Update & correction for Simplified Chinese translation

### PR DESCRIPTION
**Pull request by namolite**
## 简体中文（zh_SC）翻译更新

🩹 Updated common, npc, skills
- Fixed some semantic errors, misspellings & wrong symbols
- Translation for new game version

📝 Created body, subtitles, quest

### CODE REVIEW

**Comment by namolite** [comment]
I don't have an Gitlab account yet, sorry for if this causes any problems 😢

**Comment by juliancoffee** [comment]
I recommend going to Gitlab or jumping to our Discord into #translation channel so this PR doesn't vanish in void.

**Comment by namolite** [comment]
> I recommend going to Gitlab or jumping to our Discord into #translation channel so this PR doesn't vanish in void.

Thank you.

**Comment by namolite** [comment]
Gitlab Merge Request:
https://gitlab.com/veloren/veloren/-/merge_requests/3970

**Comment by AngelOnFira** [comment]
Closing this, as a Gitlab issue was created

**Pull request closed without merging**
